spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/marmitech}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=${PORT:8080}
app.cors.origins=${CORS_ORIGINS:http://localhost:4200}
